
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "mohasakr",
    "name": "Mohamed Sakr",
    "password": "12345678"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "root",
    "password": "sekret"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "salainen"
}


