POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "React Design Patterns",
    "date": "2021-09-30T18:39:34.091Z",
    "important": true,
    "userId": "615dbac09a01445cd00c3f81"
}

### 

POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "Scalable Node.js Application",
    "date": "2021-12-1T18:39:34.091Z",
    "important": true,
    "userId": "615dbac09a01445cd00c3f81"
}